env:
  mocha: true

extends:
  - standard
  - 'plugin:@typescript-eslint/recommended'
  - prettier

parser: '@typescript-eslint/parser'

rules:
  # We keep whitespace cleaned up.
  no-trailing-spaces: 'error'
  eol-last: 'error'

  '@typescript-eslint/explicit-function-return-type':
    ['error', { 'allowExpressions': true }]

  # Our additions.
  no-var: 'error'
  prefer-const: 'error'
  no-console: 'error'
